### PR TITLE
Import squizlabs/php_codesniffer package

### PR DESCRIPTION
**Pull request by guzzilar**
#### 1. Objective

As Omise-Magento aimed to followed the PHP code conventions/standards from [PSR standards](http://www.php-fig.org/psr/)

This CodeSniffer package will make us easily track the missing standards and help for improve readability of the code.

**Related information**:
Related issue(s): 🙅
Related ticket(s): 🙅

#### 2. Description of change

- Import squizlabs/php_codesniffer package.
- Custom rules due to Magento code structure. (see additional note)

#### 3. Quality assurance

**🔧 Environments:**

- **Latest `squizlabs/php_codesniffer` version**: 2.7.1 (stable)

**✏️ Details:**

No test for this changes, since it only include the CodeSniffer package.

#### 4. Impact of the change

No.

#### 5. Priority of change

Normal

#### 6. Additional Notes

- To install, it requires that your machine must install [Composer](https://getcomposer.org)
- To install the package, execute `composer install` from your command line (i.e. Terminal)
- To run PHP CodeSniffer package, execute `./vendor/bin/phpcs --standard=ruleset.xml --ignore=src/lib/omise-php/ src/`

- Due to Magento 1 doesn't support naming `namespace`,
  so the `PSR1.Classes.ClassDeclaration.MissingNamespace` rule must be exclude.
- Due to Magento 1 class name structure is contains by `folder_hierarchy_classname`.
  i.e. if your file is rely in folder `ModuleName/PackageName/Model/Resources/YouClass.php`, your class name must be `class ModuleName_PackageName_Model_Resources_YourClass { ... }`.

  So, `Squiz.Classes.ValidClassName.NotCamelCaps` rule must be removed to comply with the name structure.

- Exclude `PSR2.Classes.PropertyDeclaration.Underscore` rule due to Magento 1 is still prefixing their protected property by `_` (underscore) that Omise-Magento need to have the 

  i.e. https://github.com/omise/omise-magento/blob/1-stable/src/app/code/community/Omise/Gateway/Model/PaymentMethod.php#L5

- Exclude `PSR2.Methods.MethodDeclaration.Underscore` rule due to Magento 1 is still prefixing their protected method by `_` (underscore) that made Omise-Magento need to follows.

  i.e. https://github.com/omise/omise-magento/blob/1-stable/src/app/code/community/Omise/Gateway/Block/Adminhtml/Config/Edit/Form.php#L8

### CODE REVIEW

**Comment by guzzilar** [comment]
Fyi, add one more commit https://github.com/omise/omise-magento/pull/45/commits/1973cdb8466a35015566d6424f13f256266a84e7 & updated PR description

**Comment by nimid** [comment]
@guzzilar Refer to the[ Pear ruleset example](https://pear.php.net/manual/en/package.php.php-codesniffer.annotated-ruleset.php), how about add an option `<exclude-pattern>*/omise-php/*</exclude-pattern>` to the `ruleset.xml`?

So, the parameter `--ignore` when run `phpcs` via command line can be suppressed.

**Comment by guzzilar** [comment]
@nimid don't know why I can't run that command, 
Did try `./vendor/bin/phpcs --standard=ruleset.xml --ignore=*/omise-php/* src/`
Got 
```
No matches for wildcard '--ignore=*/omise-php/*'.
fish: ./vendor/bin/phpcs --standard=ruleset.xml --ignore=*/omise-php/* src/
```

**Comment by guzzilar** [comment]
@nimid ok, this one works, 
`./vendor/bin/phpcs --standard=ruleset.xml --ignore='*/omise-php/*' src/`

👆 is this you mentioned about?

**Comment by guzzilar** [comment]
:rage2: @nimid sry, I misread, you're talking about `ruleset.xml`
Ok, I agree. Will add & push code.

Thanks 👍 👍 👍

**Comment by nimid** [comment]
@guzzilar Not sure.  Without quote, double quote or single quote they can run on my environment including `src/lib/omise-php/`.

But `src/lib/omise-php/` can run on both environments, it is better.

**Comment by guzzilar** [comment]
@nimid Ok, according to Magento structure, `lib` folder contains only 3rd-party libs. So I decided to prevent it from `src/lib` instead.

**Comment by nimid** [comment]
@guzzilar Ok. This pull request can be merged.

**Comment by guzzilar** [comment]
👍

**Pull request merged**
