### PR TITLE
Update Omise-PHP library to version 2.6.0

### PR DESCRIPTION
**Pull request by guzzilar**
> This PR required PR #40 to be merged first. 
>
> Note, 👆  just because I rebased PR #40 into this branch before submit pull request. Technically, 2 PRs are not related to each other at all.

#### 1. Objective

Update Omise-PHP to the latest version, 2.6.0.

For more information about Omise-PHP 2.6.0, please check the link below.
https://github.com/omise/omise-php/releases/tag/v2.6.0

**Related information**:
Related issue(s): 🙅
Related ticket(s): 🙅

#### 2. Description of change

- Update Omise-PHP.
- Remove unused directories & files, the list are as follows:
  1 `./tests`
  2 `.gitignore`
  3 `circle.yml`
  4 `composer.json`
  5 `phpunit.xml`

#### 3. Quality assurance

**🔧 Environments:**

- **Platform**: Magento 1.9.3.1
- **Omise plugin**: Omise-Magento 1.9.0.6
- **PHP**: 5.6.28
- **Omise-PHP**: 2.6.0

**✏️ Details:**

To prove that this changed will not effect to the current function, we should consider 2 parts,
✅ 1. Test if plugin still able to connect with Omise API, go to `Plugin Dashboard` page.
    screen shot 2560-01-20 at 4 19 36 pm

✅ 2. Test create charge with normal checkout process, API should retrieve new `Omise-PHP` version, which is, 2.6.0.
    👇 I created new order, and this is the charge log.
    screen shot 2560-01-20 at 4 23 22 pm

#### 4. Impact of the change

The steps below should be mentioned in README.md in a new section `how to upgrade Omise-Magento 1.9.0.6 to 1.x`

To completely remove some unused files in `/lib/omise-php`
1. At the Magento's root directory, remove folder `./lib/omise-php`
2. Then, copy new `./lib/omise-php` from this changes and paste into `./lib`

Says, if you're using Macbook and want to copy `lib/omise-php` folder from plugin to Magento directory, click `Replace`. (not `Merge`)
screen shot 2560-01-20 at 4 36 25 pm

_**note**, this action isn't must-do action, even user doesn't follow this step, it's totally fine._
_Since this step is just to remove the following files_
```
- Remove unused directories & files, the list are as follows:
  1 `./tests`
  2 `.gitignore`
  3 `circle.yml`
  4 `composer.json`
  5 `phpunit.xml`

```

#### 5. Priority of change

Normal.

#### 6. Additional Notes

- Just to keep library version up-to-date. Doesn't has any relation with the core functions of Omise-Magento.

### CODE REVIEW

**Comment by nimid** [comment]
@guzzilar From the [Omise-PHP 2.6.0 release note](https://github.com/omise/omise-php/releases/tag/v2.6.0), could you provide the reasons or requirements to update the version?

**Comment by guzzilar** [comment]
@nimid https://github.com/omise/omise-magento/pull/42#issuecomment-275602897
Just to keep it up-to-date.

I'll add this reason into PR description 👍

**Comment by guzzilar** [comment]
https://github.com/omise/omise-magento/pull/42#issuecomment-275604199

updated to `Additional Notes`

**Comment by guzzilar** [comment]
rebased PR #40 (`1-update-omisephp-lib`) to PR #42 (`1-update-omisephp-lib`).

**Comment by guzzilar** [comment]
rebased with `1-stable`

**Comment by nimid** [comment]
@guzzilar Can This request be considered later?

This pull request has the impact to the user as mentioned in the section, 4. Impact of the change, in the pull request description and along with `Just to keep it up-to-date`.

- Is it means this pull request does not has a reason, a requirement or a function that it will delivered to the user?
- Has the old version bug?
- Is the new version has more performance such as work faster?
- Which change in Omise-PHP 2.6.0 that the features 3-D Secure or support currencies are required?

**Comment by guzzilar** [comment]
@nimid if your concern is about section 4.

It just to remove 
```
./tests
2 .gitignore
3 circle.yml
4 composer.json
5 phpunit.xml
```

Which is, if user doesn't do that, it's totally fine. (I'd mention in description).

```
- Is it means this pull request does not has a reason, a requirement or a function that it will delivered to the user?
- Has the old version bug?
- Is the new version has more performance such as work faster?
- Which change in Omise-PHP 2.6.0 that the features 3-D Secure or support currencies are required?
```

No, but in the meantime, I don't see any worse point that we shouldn't update our own library.

Also, Omise-PHP 2.6.0 solved some issues. That'd make some users/developers who want to enhance our plugin with their own requirement could have benefit with.

**Comment by guzzilar** [comment]
Updated PR description.

**Comment by guzzilar** [comment]
@nimid Also note, if we consider it later, then we just increase merchants who have 
```
./tests
2 .gitignore
3 circle.yml
4 composer.json
5 phpunit.xml
```
in their machine, which is, at the end, if they want to remove those files, they have to also do the steps in the section 4 anyway.

**Comment by guzzilar** [comment]
👍

**Pull request merged**
